apiVersion: operator.min.io/v4
kind: Tenant
metadata:
  name: minio
  namespace: minio
spec:
  image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
  podManagementPolicy: Parallel
  replicas: 1
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  mountPath: /export
  requestAutoCert: true
  users:
    - name: minio-user
      secretRef:
        name: minio-user-creds

